# **Numpy:Trabajar con arreglos y funciones matematicas de manera mas sencilla**

In [ ]:
import numpy as np

In [ ]:
np.array([10, 20, 30, 5, 55])

array([10, 20, 30,  5, 55])

In [ ]:
a = np.array([20, 40, 56, 67])

In [ ]:
a[3]

67

Indices

In [ ]:
a[1:]

array([40, 56, 67])

In [ ]:
a[1:3]

array([40, 56])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
type(np.ones(()))

numpy.ndarray